// <auto-generated />
namespace OP.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MonitorCondition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MonitorCondition));
        
        string IMigrationMetadata.Id
        {
            get { return "201703010215075_MonitorCondition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
