// <auto-generated />
namespace OP.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170621Monitor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170621Monitor));
        
        string IMigrationMetadata.Id
        {
            get { return "201706210238267_20170621Monitor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
